# #load our libraries pls
# pkgs <- c("shinydashboard","shiny","plotly",
#           "tidyr","reshape2","gridExtra","tidyverse", "caTools","easypackages")
# install.packages(pkgs,dependencies = T)
# library(easypackages)
# libraries(pkgs)
library(htmltools)
library(dygraphs)
library(plotly)
library(shinydashboard)
library(shiny)
library(ggplot2)
library(tidyverse)
library(crosstalk)

#read in data and generate necessary alpha_theta_vec very quickly
dash_data <- readRDS("dashboard.data.fitnesses.2.rds")

alpha_theta_vec <- c(seq(0,.1,.01),seq(0.2,0.5,0.1))
testy_list <- dash_data[[1]]
indices <- dash_data[[2]]
for(i in 1:441){
  testy_list[[i]][[2]]$dependencies[[2]]$src$file <- crosstalkLibs()[[1]]$src$file
  testy_list[[i]][[2]]$dependencies[[3]]$src$file <- crosstalkLibs()[[2]]$src$file
  testy_list[[i]][[3]]$dependencies[[2]]$src$file <- crosstalkLibs()[[1]]$src$file
  testy_list[[i]][[3]]$dependencies[[3]]$src$file <- crosstalkLibs()[[2]]$src$file
}
#remove unnecessary and large duplicate of our data
rm(dash_data)


#Here's the user interface section of the app, that has all of our menu items
#along with the contents of each tab.
ui <- dashboardPage(
  dashboardHeader(title="Trait Matching Fitness"),
  dashboardSidebar(
    sidebarMenu(
      menuItem("Indepedendent Surfaces", tabName="Indplots",icon=icon("bar-chart-o")),
      menuItem("SBS Indepependent Surfaces", tabName="SBSInd",icon=icon("bar-chart-o")),
      menuItem("Joint Surface", tabName = "Jplots", icon=icon("bar-chart-o")),
      menuItem("SBS Joint Surface", tabName="SBSJoint",icon=icon("bar-chart-o")),
      menuItem("Gifs",tabName="PopulationGifs",icon=icon("video"))
    )
  ),
  dashboardBody(
    
    tabItems(
      tabItem(tabName = "Indplots",
              h2("Individual Fitness Plots"),
              h4("Introduction"),
              p(h6("This tab has individual fitness plots. In this case, each surface rendered shows the phenotype by phenotype fitness for a single species. I have arbitrarily set the biotic optima to 3 and 1, and these remain constant through all tabs.")),
              p(h6("Beneath the plot, you can alter the parameterization of the model by choosing different abiotic and biotic alpha values as well as playing with the balance between g and chi. I coded this such that g = 1 - chi, and so as you alter chi, you also automatically alter g.")),
              h4("Caveat"),
              p(h6("The main problem with these plots its that they show two separate optima, defined by a combination of trait matching and abiotic conditions. Neither of these optima could really be inhabited by the system though, as a given maximum for one species has very low fitness for the other. For a more realistic approximation of system-wide fitness, see the Joint Plots tab.")),
              fluidRow(
                textOutput("selected_var"),
                plotlyOutput("IndSingle")
                
              ),
              fluidRow(
                shinydashboard::box(
                  sliderInput("BioAlpha", 
                              "Choose biotic alpha", 
                              min=0,max=3,step=0.5,value=0)),
                shinydashboard::box(
                  sliderInput("AbioAlpha",
                              "Choose Abiotic alpha",
                              min=0,max=3,step=0.5,value=0)
                )
                
              ),
              fluidRow(
                box(
                  sliderInput("selectSquig",
                              "Choose Trait-Matching Proportion (Squig)",
                              min=0.1,max=0.9,step=0.1,value=0.1)
                )
              )
              
              
              
              
      ),
      tabItem(tabName = "SBSInd",
              h2("Side-by-Side Individual Fitness Plots"),
              p(h6("Here you can compare the fitness surfaces generated by two different parameterizations of the underlying model.")),
              fluidRow(
                shinydashboard::box(
                  textOutput("selected_var1"),
                  plotlyOutput("IndSBS1")
                ),
                shinydashboard::box(
                  textOutput("selected_var2"),
                  plotlyOutput("IndSBS2")
                )
                
              ),
              fluidRow(
                shinydashboard::box(
                  sliderInput("BioAlpha1", 
                              "Choose biotic alpha", 
                              min=0,max=3,step=0.5,value=0),
                  sliderInput("AbioAlpha1",
                              "Choose Abiotic alpha",
                              min=0,max=3,step=0.5,value=0)
                ),
                
                shinydashboard::box(
                  sliderInput("BioAlpha2",
                              "Choose biotic alpha",
                              min=0,max=3,step=0.5,value=0),
                  sliderInput("AbioAlpha2",
                              "Choose Abiotic alpha",
                              min=0,max=3,step=0.5,value=0)
                )
                
              ),
              fluidRow(
                box(
                  sliderInput("selectSquig1",
                              "Choose Trait-Matching Proportion (Squig)",
                              min=0.1,max=0.9,step=0.1,value=0.1)
                ),
                box(
                  sliderInput("selectSquig2",
                              "Choose Trait-Matching Proportion (Squig)",
                              min=0.1,max=0.9,step=0.1,value=0.1)
                )
              )
              
              
              
              
              # fluidRow(
              #   splitLayout(cellWidths = c("50%","50%"),plotlyOutput("test"),plotlyOutput("test"))
              # )
              
              
      ),
      tabItem(
        h2("Joint Fitness Plots"),
        h4("Introduction"),
        p(h6("This tab displays 'joint fitness plots.' These are really just the element-by-element product of the two fitness matrices from the individual plots.")),
        p(h6("So, for example, if at the phenotype combination of 6 for species one and 8 for species two we had fitnesses of 0.3 and 0.6 respectively, the joint fitness would 0.18. These plots roughly represent the probability that a system could occupy any given location in phenotype-by-phenotype space.")),
        p(h6("Like before, you can use the sliders at the bottom to test different parameterizations for both abiotic and biotic alphas as well as the balance betwen g and chi. I've coded it such that g is defined as 1-chi, so as you change the value of chi, you also by definition change g.")),
        tabName = "Jplots",
        fluidRow(
          textOutput("selectedVar6"),
          plotlyOutput("JointSingle")
        )
        ,
        fluidRow(
          shinydashboard::box(
            sliderInput("BioAlpha6",
                        "Choose Biotic Alpha",
                        min=0,max=3,step=0.5,value=0)),
          shinydashboard::box(
            sliderInput("AbioAlpha6",
                        "Choose Abiotic Alpha",
                        min=0,max=3,step=0.5,value=0)
          )
          
        ),
        fluidRow(
          box(
            sliderInput("selectSquig6",
                        "Choose Trait-Matching Proportion (Squig)",
                        min=0.1,max=0.9,step=0.1,value=0.1)
          )
        )
        
        
      ),
      tabItem(
        h2("Side by Side Joint Fitness Plots"),
        tabName = "SBSJoint",
        fluidRow(
          shinydashboard::box(
            textOutput("selectedVar3"),
            plotlyOutput("JointSBS1")
          ),
          shinydashboard::box(
            textOutput("selectedVar4"),
            plotlyOutput("JointSBS2")
          )
        ),
        fluidRow(
          shinydashboard::box(
            sliderInput("BioAlpha3",
                        "Choose Biotic Alpha",
                        min=0,max=3,step=0.5,value=0),
            sliderInput("AbioAlpha3",
                        "Choose Abiotic Alpha",
                        min=0,max=3,step=0.5,value=0)
          ),
          shinydashboard::box(
            sliderInput("BioAlpha4",
                        "Choose Biotic Alpha",
                        min=0,max=3,step=0.5,value=0),
            sliderInput("AbioAlpha4",
                        "Choose Abiotic Alpha",
                        min=0,max=3,step=0.5,value=0)
          )
        ),
        fluidRow(
          box(
            sliderInput("selectSquig3",
                        "Choose Trait-Matching Proportion (Squig)",
                        min=0.1,max=0.9,step=0.1,value=0.1)
          ),
          box(
            sliderInput("selectSquig4",
                        "Choose Trait-Matching Proportion (Squig)",
                        min=0.1,max=0.9,step=0.1,value=0.1)
          )
        )
      ),
      tabItem(
        h2("How matching changes with additive genetic variance"),
        p(h6("While exploring these surfaces, I realized that a given population, even when perfectly occupying an adaptive peak, would be unlikely to remain there. Since I've hard-coded genetic variance into the model, which is to say, offspring can vary by a fixed amount from the average of the parental phenotype, phenotypes will always spread with each generation. As a result, the mean of the population is unlikely to reside at a trait matching optimum unless genetic variance is low enough that they can occupy that narrow peak without spilling over. The more they spill over, the more the mean will slide down that slope towards the next local optimum, defined by the combination of theta values.")),
        tabName="PopulationGifs",
        fluidRow(
          column(6,
                 selectInput("newAbioGif",
                             "Choose Abiotic Alpha",
                             choices = alpha_theta_vec))
          
        ),
        fluidRow(
          column(6,div(style="height:0px"),
                 plotOutput("Gifs.gifs"))
        )
    

      )
    )
  )
)



#Here's the server side which selects each data set we want to view based on
#input from the UI, then renders them and passes them back to the UI for
#display. At least from what i can tell that's what all of these do.


server <- shinyServer(function(input,output){
  
  output$Gifs.gifs <- renderImage({
    # When input$n is 1, filename is ./images/image1.jpeg
    filename <- paste("gifs.on.gifs.on.gifs/Alpha.",input$newAbioGif,".plus.var.gif",sep="")
    
    # Return a list containing the filename
    list(src = filename)
  }, deleteFile = FALSE)
  
  
  output$IndSingle <- renderPlotly({
    
    #print(input$selectPlot)
    
    #Didn't manage to get that work frown fuckin face
    
    #ind <- which(full_grid$alpha==0 & full_grid$alpha_theta==0 & full_grid$squig==0.3)
    
    
    ind <- which(indices$alpha==input$BioAlpha & indices$alpha_theta==input$AbioAlpha & near(indices$squig,input$selectSquig))
    
    testy_list[[ind]][[2]]
    
  #   which(==0 & indices$alpha_theta==0 & indices$squig==0.70)
  #   
  # 
  # which(near(c(indices$alpha,indices$alpha_theta,indices$squig),c(0,0,0.7)))
  # near(c(indices$alpha,indices$alpha_theta,indices$squig),c(0,0,0.7))
    
    # plant_plot <- variable_plot_list[[which(alpha_theta_vec==input$selectAbio)]][[which(alpha_vec==input$selectPlot)]][[2]]
    # # #pol_plot <- test_plot_list[[input$selectPlot]][[3]]
    # plant_plot
    # 
    
  })
  output$IndSBS1 <- renderPlotly({
    
    ind <- which(indices$alpha==input$BioAlpha1 & indices$alpha_theta==input$AbioAlpha1 & near(indices$squig,input$selectSquig1))
    
    testy_list[[ind]][[2]]
    #variable_plot_list[[which(alpha_theta_vec==input$selectAbio1)]][[which(alpha_vec==input$selectPlot1)]][[2]]
  })
  output$IndSBS2 <- renderPlotly({
    
    ind <- which(indices$alpha==input$BioAlpha2 & indices$alpha_theta==input$AbioAlpha2 & near(indices$squig,input$selectSquig2))
    
    testy_list[[ind]][[2]]
    #variable_plot_list[[which(alpha_theta_vec==input$selectAbio2)]][[which(alpha_vec==input$selectPlot2)]][[2]]
  })
  output$JointSBS1 <- renderPlotly({
    
    ind <- which(indices$alpha==input$BioAlpha3 & indices$alpha_theta==input$AbioAlpha3 & near(indices$squig,input$selectSquig3))
    
    testy_list[[ind]][[3]]
    #variable_plot_list[[which(alpha_theta_vec==input$AbioAlpha3)]][[which(alpha_vec==input$BioAlpha3)]][[4]]
  })
  output$JointSBS2 <- renderPlotly({
    ind <- which(indices$alpha==input$BioAlpha3 & indices$alpha_theta==input$AbioAlpha4 & near(indices$squig,input$selectSquig4))
    
    testy_list[[ind]][[3]]
    
    #variable_plot_list[[which(alpha_theta_vec==input$AbioAlpha4)]][[which(alpha_vec==input$BioAlpha4)]][[4]]
    
  })
  
  output$JointSingle <- renderPlotly({
    
    ind <- which(near(indices$alpha,input$BioAlpha6) & near(indices$alpha_theta,input$AbioAlpha6) & near(indices$squig,input$selectSquig6))
    
    testy_list[[ind]][[3]]
    #variable_plot_list[[which(alpha_theta_vec==input$AbioAlpha6)]][[which(alpha_vec==input$BioAlpha6)]][[4]]
  })
  
})

#test_plot_list`1`[[1]]
#test_plot_list[[1]][[2]]

#test_plot_list[[1]][[3]]


